#!/usr/bin/env bash
# script that transfers a file from our client to a server
# Assigning parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Check if number of parameters is less than 3
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
else
	scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
fi