#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
file=/var/run/myscript.pid
echo $$ > "$file"
trap 'rm -f $file; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo I hate the kill command; rm -f $file; exit' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done