#!/usr/bin/env bash
# Script that displays "bad luck" on the 4th iteration, "good luck" on the 8th iteration and "Best School" on all the other iterations
counter=1
while [ "$counter" -le 10 ]; do
    if [ "$counter" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$counter" -eq 8 ]
    then 
        echo "good luck"
    else
        echo "Best School"
    fi
        counter=$((counter + 1))
done