#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
cp /etc/hosts ~/hosts.new

#  **** localhost resolves to 127.0.0.2
echo "127.0.0.2		localhost" > ~/hosts.new

#  **** facebook.com resolves to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Forcing this command
cp -f ~/hosts.new /etc/hosts